export const SHOW_FIRST = 'TUTORIAL_TOAST/SHOW_FIRST';
export const SHOW_NEXT = 'TUTORIAL_TOAST/SHOW_NEXT';
export const SHOW_PREV = 'TUTORIAL_TOAST/SHOW_PREV';
export const HIDE_TOAST = 'TUTORIAL_TOAST/HIDE_TOAST';
